### ISSUE TITLE
typescript definitions

### ISSUE THREAD

**Issue by zpdDG4gta8XKpMCd** [Streampunk/beamcoder#17]
quick googling didn't bring anything

are there typescript definitions of some sort?

if no, any plans to add them?

**Comment by sparkpunkd** [comment]
No. No typescript definitions yet. I have only recently started working on Typescript-based projects since writing beamcoder. I agree it would be good to add them.

I hope to have a project that needs typescript with beamcoder within a few months so I expect this will happen, but it won't be straight away.

**Comment by alexandrucancescu** [comment]
I am working on some definitions. You can use already use them:

https://github.com/alexandrucancescu/beamcoder-typings

using `npm i -D alexandrucancescu/beamcoder-typings` though you might need to go into **node_modules/@types** and rename **beamcoder-typings** folder to **beamcoder**.

When they are finished I will do a pull request to DefinetelyTyped
