### ISSUE TITLE
Locking issues with >3 concurrent video streams

### ISSUE THREAD

**Issue by mandersan** [Streampunk/beamcoder#7]
I've noticed that attempting to demux more than 3 videos concurrently results in the Node application locking up completely.

The following reproduction sample pipes a small video file into beamcoder. It does so asynchronously and waits for all streams to complete. On running this you will see that nothing is printed after the Beamcoder startup banner text. If you remove one of the tags on line 31 (so that only 3 streams are created) you'll see that all 3 are read successfully to completion.

[https://gist.github.com/mandersan/00df1955d551fc225c7eec9191cf9613/raw/3939f2b9ba46f2e7da4b0214c9133888f668ff7f/beamcoder-test.zip](url)

Thanks

**Comment by scriptorian** [comment]
Hi, Thanks very much for the report and for the test files!
I have made a small change that delays the start of reading (initialise of demux does a read) until the source has started to send writes, otherwise the node thread never gets to do the writes. The problem seems to be something to do with the node thread pool but I couldn't crack it satisfactorily. Please let us know if this change fixes the problem for you or if you have any other insights.
